version: "3.9"

services:
  fornt:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: front-end
    volumes:
      - ./front-end:/app
    ports:
      - 3000:3000
    networks:
      - rplumber-network
    depends_on:
      - rplumber
  rplumber:
    build: .
    container_name: r-plumber
    volumes:
      - ./:/app
      - ./api.R:/app/api.R
    ports:
      - 8000:8000
    mem_limit: 1g
    networks:
      - rplumber-network

networks:
  rplumber-network:
    driver: bridge
