version: "3"

services:
  fornt:
    build: ./front-end
    container_name: front-end
    volumes:
      - ./:./app
    ports:
      - 3000:3000
    networks:
      - rplumber-network
  rplumber:
    build: .
    container_name: r-plumber
    volumes:
      - ./:/app
      - ./api.R:/app/api.R
    ports:
      - 8000:8000
    mem_limit: 1g
    networks:
      - rplumber-network
  ngnix:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - 80:80
    depends_on:
      - rplumber
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - rplumber-network

networks:
  rplumber-network:
    driver: bridge
